name: Daily Finance Report

on:
  schedule:
    - cron: "0 1 * * *"   # 每天北京时间 09:00 执行
  workflow_dispatch:      # 手动运行按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: python daily_report.py

