name: 每日金融数据日报

on:
  schedule:
    - cron: "0 1 * * *"   # 每天 UTC 1点运行，北京时间=9点
  workflow_dispatch:       # 允许手动触发

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install requests

      - name: 运行日报脚本
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python daily_report.py
